### PR TITLE
Improve `MemoryIO`

### PR DESCRIPTION
**Pull request by mundya**
- Improves the `seek` docstring to mention `os.SEEK_CUR` and friends.
 - If `read` is called with no (or negative) argument then it is interpreted as being a read until the end of the memory region.
 - Implements the suggestions from #68 
 - flake8

### CODE REVIEW

**Comment by mossblaser** [comment]
`alloc_next_as_io` -> `create_view` or `create_slice`?

Perhaps?

Aside from that, that looks fair, I think!

**Comment by mundya** [comment]
I like `create_view`... I'm not so good at naming things.

(Though better than some, tennis was originally called ["Sphairistiké"](http://www.britannica.com/EBchecked/topic/587387/tennis))

**Comment by mundya** [comment]
Hold off on this, I'd like to try something else.

**Comment by mundya** [comment]
I'd like to merge this soonish, I've removed `create_view` until we can decide better semantics for it.  I've also renamed `MachineControl.sdram_alloc_as_io` to `sdram_alloc_as_filelike`.  I'm currently reading up on the correct way to present memoryviews.

**Comment by mossblaser** [comment]
Fair enough. I've updated the docs. Assuming travis doesn't barf I'll merge that in ASAP.

**Pull request merged**
