### PR TITLE
Remove individual authors from docs.

### PR DESCRIPTION
**Pull request by mundya**
Replace with 'the Rig Project'.

### CODE REVIEW

**Comment by mossblaser** [comment]
Maybe Project Rig(?) I'll leave that to your discretion!

Otherwise, sounds fair!

**Comment by mundya** [comment]
I guess that would match the Git organisation, I'll change and merge.

**Comment by mundya** [comment]
Travis is slow...

**Comment by mossblaser** [comment]
We need more spinnaker boards in the pool :P

LGTM! Merging [post travis] ;)

**Pull request merged**
