### PR TITLE
Add type cast documentation

### LINKED ISSUE #87: `type_casts` not in documentation

### PR DESCRIPTION
**Pull request by mundya**
- Fixes #87 
 - Also fixes an embarrassing bug in fix->float conversions.
 - Modifies the `tox.ini` to run doctests and unit tests separately.
 - Modifies `pytest.ini` to run doctests in docstrings wherever possible.

### CODE REVIEW

**Comment by mundya** [comment]
Ug weird doctest failures...

**Comment by mossblaser** [comment]
Ah... that'll be the bizarro numpy mocking going on for the benefit of RTD...

**Comment by mossblaser** [comment]
Pending travis, LGTM!

Rigged

**Comment by mundya** [comment]
Danke!

**Pull request merged**
