### PR TITLE
Add BitField.get_tags (Implements #85)

### PR DESCRIPTION
**Pull request by mossblaser**
As requested in #85 by @mundya, allows getting the set of tags a field has:

    >>> from rig.bitfield import BitField
    >>> bf = BitField(32)
    >>> bf.add_field("test", tags="TestTag")
    >>> bf(test=0).add_field("test0", tags="Test0Tag")
    >>> bf(test=1).add_field("test1", tags="Test1Tag")

    >>> bf.get_tags("test")
    {"TestTag", "Test0Tag", "Test1Tag"}

    >>> bf.get_tags("test0")
    {"Test0Tag"}

### CODE REVIEW

**Comment by mundya** [comment]
Also, ug Python 2 and 3 doctests...

**Comment by mundya** [comment]
@mossblaser I believe I've fixed the docttest.

**Comment by mossblaser** [comment]
Awesome, thanks! :)

**Comment by mossblaser** [comment]
(also, doctest is lame... :()

**Comment by mundya** [comment]
Assuming this passes this all LGTM, I'll leave it to you to check my changes are acceptable :smile: 

Thank you!

**Pull request merged**
