### PR TITLE
Output from annealing iteration congests INFO channel

### PR DESCRIPTION
**Pull request by neworderofjamie**
Maybe?

### CODE REVIEW

**Comment by mossblaser** [comment]
This seems reasonable to me since it seems borderline DEBUG/INFO anyway. If you could make flake8 happy (add an extra space to the broken lines) I'd say this is good to merge :).

As an aside, can't you filter out non-nengo related logging info with Python's logging stuff?

**Comment by neworderofjamie** [comment]
what's it whining about now? it's all aligned n'shit..

**Comment by mossblaser** [comment]
> `god, I detest pep8`

Haha. Anyway, looks good to me!

**Comment by mundya** [comment]
> As an aside, can't you filter out non-nengo related logging info with Python's logging?

You can but it's a little annoying.

**Comment by mossblaser** [comment]
> You can but it's a little annoying.

Sigh... that library fails miserably at being pleasant to use for common use-cases. :(

**Pull request merged**
