### PR TITLE
Fix incorrect variable name.

### PR DESCRIPTION
**Pull request by mossblaser**

### CODE REVIEW

**Comment by mundya** [comment]
LGTM.

**Comment by mundya** [comment]
Do we have a test that checks what happens when this is done?  The line must have been being executed, but were we checking what other things occurred?

**Comment by mossblaser** [comment]
We do not. I've just been trying to think of a sensible test which would catch this bug but am struggling...

**Comment by mundya** [comment]
Probably not worth it... :worried:

**Comment by mossblaser** [comment]
Yeah :/ as much as I like all bug fixes to come with a test, this doesn't seem like a sensible time for that.

**Pull request merged**
