### PR TITLE
Add a common Makefile which uses the ST release of SpiNNaker tools

### PR DESCRIPTION
**Pull request by mundya**
Adds a new (overly complex) Makefile that works directly with Steve Temple's releases of the SpiNNaker software tools.  The Makefile should be usable by many other projects and they are welcome to copy it.

`Makefile.common` could fall over if `SPINN_DIRS`.  @mossblaser / @neworderofjamie any thoughts?

### CODE REVIEW

**Comment by mossblaser** [comment]
Very glad to see things getting cleaner/receiving more thought in this space!

Is it not possible to build nicely with what ST provides verbatim without a new "common" makefile base?

Having asked ST about how best to build things he sounded very open to suggestions/contributions in this space. As such I'd much prefer this be contributed upstream rather than vendoring here since it isn't really Rig's place to do so. Certainly, it saves maintenance and everyone gets to benefit!

**Comment by mundya** [comment]
> Is it not possible to build nicely with what ST provides verbatim without a new "common" makefile base?

Yes.

`diff <ST Makefile> <This Makefile>`

```diff
6a7,8
> ## (Heavily) based on a Makefile by Steve Temple.  Bastardised by Andrew Mundy.
> ##
8a11,27
> ## =============================================================================
> ##
> ## Usage
> ##
> ## =============================================================================
> ##
> ## This Makefile is intended to be included in an another Makefile.  It will
> ## build the target APP_DIR/APP.aplx when the following variables are set:
> ##
> ##  - APP - the name of the APLX file to build
> ##  - APP_DIR - the directory in which to place the APLX
> ##  - SOURCES - all the C files which are required to build the APLX
> ##
> ## For sample usage please see `test_aplx/Makefile`.
> ##
> ## =============================================================================
> 
140a160
> 	cp $(APP).aplx $(APP_DIR)/
142c162
< 	$(LS) $(APP).aplx
---
> 	$(LS) $(APP_DIR)/$(APP).aplx
167,168d186
< 	$(RM) $(OBJECTS) $(APP).elf $(APP).txt
< clean:
169a188,189
> clean: tidy
> 	$(RM) $(APP_DIR)/$(APP).aplx
```

**Comment by mundya** [comment]
Hmm... there should be more than that.

The only major change is:
```makefile
# Build the object files
.c.o: $(INC_DIR)/spinnaker.h $(INC_DIR)/sark.h $(INC_DIR)/spin1_api.h
	$(CC) $(CFLAGS) $< -o $@
```

**Comment by mossblaser** [comment]
In that case, I'd very strongly suggest submitting this patch upstream rather than forking it into Rig. I'm sure ST'd be happy to have it [though I don't grok make enough to really know what is going on here ;)].

**Comment by mundya** [comment]
Actual diff:
```diff
3c3
< ## Makefile        Makefile for a simple SpiNNaker application
---
> ## Makefile        Makefile for a SpiNNaker application
7,9c7
< ## Author          Steve Temple, APT Group, School of Computer Science
< ##
< ## Email           temples@cs.man.ac.uk
---
> ## (Heavily) based on a Makefile by Steve Temple.  Bastardised by Andrew Mundy.
13,26c11,26
< # Makefile for a simple SpiNNaker application. This will compile
< # a single C source file into an APLX file which can be loaded onto
< # SpiNNaker. It will link with either a 'bare' SARK library or a
< # combined SARK/API library.
< 
< # The options below can be overridden from the command line or via
< # environment variables. For example, to compile and link "my_example.c"
< # with the ARM tools and generate ARM (as opposed to Thumb) code
< #
< # make APP=my_example GNU=0 THUMB=0
< 
< # Name of app (derived from C source - eg sark.c)
< 
< APP := sark
---
> ## =============================================================================
> ##
> ## Usage
> ##
> ## =============================================================================
> ##
> ## This Makefile is intended to be included in an another Makefile.  It will
> ## build the target APP_DIR/APP.aplx when the following variables are set:
> ##
> ##  - APP - the name of the APLX file to build
> ##  - APP_DIR - the directory in which to place the APLX
> ##  - SOURCES - all the C files which are required to build the APLX
> ##
> ## For sample usage please see `test_aplx/Makefile`.
> ##
> ## =============================================================================
131a132
> CP  := \cp
139,140c140
< # List of objects making up the application. If there are other files
< # in the application, add their object file names to this variable.
---
> # Construct the list of objects from the list of targets.
142c142
< OBJECTS := $(APP).o
---
> OBJECTS=$(SOURCES:.c=.o)
162c162,163
< 	$(LS) $(APP).aplx
---
> 	$(CP) $(APP).aplx $(APP_DIR)/
> 	$(LS) $(APP_DIR)/$(APP).aplx
172c173
< $(APP).elf: $(OBJECTS) $(SCRIPT) $(LIBRARY) 
---
> $(APP).elf: $(OBJECTS) $(SCRIPT) $(LIBRARY)
179,185c180,182
< 
< # Build the main object file. If there are other files in the
< # application, place their build dependencies below this one.
< 
< $(APP).o: $(APP).c $(INC_DIR)/spinnaker.h $(INC_DIR)/sark.h \
< 	  $(INC_DIR)/spin1_api.h
< 	$(CC) $(CFLAGS) $(APP).c
---
> # Build the object files
> .c.o: $(INC_DIR)/spinnaker.h $(INC_DIR)/sark.h $(INC_DIR)/spin1_api.h
> 	$(CC) $(CFLAGS) $< -o $@
191,192d187
< 	$(RM) $(OBJECTS) $(APP).elf $(APP).txt
< clean:
193a189,190
> clean: tidy
> 	$(RM) $(APP_DIR)/$(APP).aplx
```

(I'd accidentally overwritten the original Makefile :worried:)

**Pull request closed without merging**
