### PR TITLE
Fix SC&MP app_stop

### PR DESCRIPTION
**Pull request by mossblaser**
This branch is actually off #206 which should be merged first!

This branch adds a new SC&MP with fixed app_stop and removes the workaround code in rig.

### CODE REVIEW

**Comment by mossblaser** [comment]
Yuck... Check out the bug that was just squashed... Anyway, the last commit should give greater confidence to the claim that this is all working.

**Comment by mossblaser** [comment]
Merge if/when you're happy :) Thanks!

**Comment by mundya** [comment]
Will review this after #206 is merged, it'll make it a little clearer where the relevant changes are. Sorry.

**Comment by mundya** [comment]
LGTM, merging...

**Pull request merged**
